modLoader="javafml"
loaderVersion="[44,)"
#issueTrackerURL=""
license="MIT"

[[mods]]
modId="antixray"
version="${version}"
displayName="AntiXray"
authors="Drex"
description='''
This mod implements Papers 0367-Anti-Xray.patch!
'''
#logoFile=""

[[dependencies.antixray]]
modId="forge"
mandatory=true
versionRange="[44,)"
ordering="NONE"
side="BOTH"

[[dependencies.antixray]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"

[custom.mc-publish]
modrinth="sml2FMaA"
curseforge=560511