modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL=""
license = "MIT"

[[mods]]
modId = "antixray"
version = "${mod_version}"
displayName = "AntiXray"
authors = "Drex"
description = '''
This mod implements Papers 0367-Anti-Xray.patch!
'''
