modLoader="javafml"
loaderVersion="[41,)"
#issueTrackerURL=""
license="MIT"

[[mods]]
modId="antixray"
version="${version}"
displayName="AntiXray"
authors="Drex"
description='''
This mod implements Papers 0367-Anti-Xray.patch!
'''
#logoFile=""

[[dependencies.antixray]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"

[[dependencies.antixray]]
modId="minecraft"
mandatory=true
versionRange="[1.19]"
ordering="NONE"
side="BOTH"
