# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Minecraft Properties
minecraft_version=26.3
curseforge_minecraft_versions=26.3
modrinth_minecraft_versions=26.3
neoforge_version=26.3.0.6-beta
loader_version=0.19.5

# Mod Properties
mod_version=1.4.16
maven_group=me.drexhd
archives_base_name=antixray

# Other Dependencies
toml_version=0.7.2
fabric_api_version=0.160.7+26.3
fabric_permission_api_version=0.7.0

# Compat
fabric_imm_ptl_core_version=v6.0.6-mc1.21.1
